apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dgup
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-flcl-tenant/byoc-app-cryj/dgup@sha256:53f7f07c76ba5aa819d0d66afe591f91f275e2bf8e18922be04a30d312753119
        name: my-java-quarkus
        resources: {}
status: {}
