apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dgup
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dgup
    app.kubernetes.io/part-of: byoc-app-cryj
  name: dgup
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: dgup
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: dgup
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-flcl-tenant/byoc-app-cryj/dgup@sha256:53f7f07c76ba5aa819d0d66afe591f91f275e2bf8e18922be04a30d312753119
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
