apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dgup
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dgup
    app.kubernetes.io/part-of: byoc-app-cryj
  name: dgup
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: dgup
status:
  loadBalancer: {}
